Adding python script for setting desktop background

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -13,6 +13,7 @@ sub_help () {
     echo "   update             Update packages and pkg managers: OS X Applications, Homebrew/Cask, npm, Ruby, and pip"
     echo "   osx                Apply OS X system defaults"
     echo "   dock               Apply OS X Dock settings"
+    echo "   install beets      Install Beets (PIP)"
     echo "   install mjolnir    Install Mjolnir (Homebrew/Luarocks)"
     echo "   install vundle     Install Vundle"
 }
@@ -49,8 +50,8 @@ sub_dock () {
 }
 
 sub_install () {
-    local SCRIPT="$DOTFILES_DIR/install/$SUB_COMMAND_NAME.sh"
-    [ -f "$SCRIPT" ] && . "$SCRIPT" || echo "Unable to find script to install $SUB_COMMAND_NAME"
+    local SCRIPT="${DOTFILES_DIR}/install/${SUB_COMMAND_NAME}.sh"
+    [ -f "$SCRIPT" ] && . "$SCRIPT" || echo "Unable to find script to install ${SUB_COMMAND_NAME}"
 }
 
 # Make sure to keep this in sync with the available public commands
